### ISSUE TITLE
Validate URL with a regular expresion

### ISSUE THREAD

**Issue by merlinnusr** [gkbrk/slowloris#20]

**Comment by Jul10l1r4** [comment]
Whatt? Is impossible, this do not is a route, this is url address, and no route for navegation. the google make this.

**Comment by JChamblee99** [comment]
https://stackoverflow.com/questions/161738/what-is-the-best-regular-expression-to-check-if-a-string-is-a-valid-url
A decent solution:
`/((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[\w]*))?)/`

**Comment by Jul10l1r4** [comment]
But it are routes, ex: 
```js
get("/home", function(...
```
For explore url, not work... You can search for bruteforce path

**Comment by JChamblee99** [comment]
I'm not sure if there's a language disconnect here, but I don't see how that has to do with URL validation.
This is about website links like "www.example.com".

**Comment by gkbrk** [comment]
I don't see why we should do URL validation at all. If the socket can't connect or make requests, it just won't work. This will be obvious because the output will say there are 0 connected sockets.

It might be a good idea to make it throw an error in case no sockets can connect, but I don't see the point of doing validations with regex. It either connects or it doesn't. The fact that it's a valid domain/IP provides no guarantee that a connection can be established.
