### ISSUE TITLE
Socket Count sent is 0

### ISSUE THREAD

**Issue by Imagine-YT** [gkbrk/slowloris#59]
C:\Users\ASUS\Downloads\slowloris-master>py slowloris.py HIDDEN IP -s 500
[02-09-2021 10:24:46] Attacking HIDDEN IP with 500 sockets.
[02-09-2021 10:24:46] Creating sockets...
[02-09-2021 10:24:50] Sending keep-alive headers... Socket count: 0
[02-09-2021 10:25:09] Sending keep-alive headers... Socket count: 0
[02-09-2021 10:25:28] Sending keep-alive headers... Socket count: 0
![image](https://user-images.githubusercontent.com/74649094/131784240-263b2faa-8a93-4177-ad3a-42b949f14189.png)

**Comment by debian-user-france1** [comment]
Hmm I never had such thing
Maybe you should try it for another URL or look into the code

**Comment by thunderking2111** [comment]
you should try using -v option with your command...

> **python slowloris.py IPADDR -s 500 -v**

so it will give you where the problem is .. In my case it was giving me this output..
![Screenshot from 2021-09-18 12-27-16](https://user-images.githubusercontent.com/53564919/133906467-951de805-719f-4512-8e9d-6d36fe4bb444.png)

So as you can see the victim is not accepting the connection request. Which means the remote port is not open or it is not listening. Now by default this script uses port no 80 as remote port. So you should consider starting port no 80. 
In my case i started apache2 server which by default starts port no 80 so the problem was resolved.

In windows you should you will have to create an inbound rule for TCP port 80 in windows defender firewall. You will be able to find it on google by searching 

> **how to start port 80 on windows**

.

**Comment by Droid-MAX** [comment]
[Errno 7] No address associated with hostname
